[package]
name = "quic-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = "0.11.7"
tokio = { version = "1", features = ["full"] }
rustls = "0.23.25"
rcgen = "0.13.2"
rustls-pki-types = "1.11.0"
